/**
 * Auto-ingested Distraction Watch stubs (DIST-AUTO-*).
 * Regenerated by: npm run refresh:distracted (scripts/update-distracted-data.ts)
 *
 * DEFAULT: empty. FR→Distracted requires DISTRACTED_FR_AUTO=1.
 * Curated narrative entries live in distractions.ts.
 */
import type { DistractionEntry } from "@/lib/types";

export const autoDistractedEntries: DistractionEntry[] = [] as DistractionEntry[];

export const autoDistractedMeta = {
  "generatedAt": "2026-07-20T15:30:25.756Z",
  "lookbackDays": 21,
  "frAutoEnabled": false,
  "rssAutoEnabled": false,
  "congressAutoEnabled": false,
  "frFetched": 0,
  "frCandidates": 0,
  "rssFetched": 0,
  "congressCount": 0,
  "newlyAddedCount": 0,
  "autoEntryCount": 0,
  "curatedIdCount": 48,
  "note": "Curated-only: FR→Distracted disabled (DISTRACTED_FR_AUTO!=1)"
} as const;
