/**
 * Auto-ingested Distraction Watch stubs (DIST-AUTO-*).
 * Regenerated by: npm run refresh:distracted (scripts/update-distracted-data.ts)
 *
 * Do not hand-edit - curated narrative entries live in distractions.ts
 * (merged there with autoDistractedEntries).
 */
import type { DistractionEntry } from "@/lib/types";

export const autoDistractedEntries: DistractionEntry[] = [
  {
    "id": "DIST-AUTO-20260720-2026-14654",
    "date": "2026-07-20",
    "title": "Action by the United States in the Investigation Under Section 301 of the Trade Act of 1974 of Brazil's Acts, Policies, and Practices Related to Digital Trade and Electronic Payment Services; Unfair, Preferential Tariffs; Anti-Corruption Enforcement; Intellectual Property Protection; Ethanol Market Access; and Illegal Deforestation",
    "distraction": "Official FR spotlight: Action by the United States in the Investigation Under Section 301 of…",
    "coveringUp": "Same-day tracker severity, disclosure fights, or floor votes this may bury.",
    "whyTheyDoIt": "A fresh official action steals oxygen from accountability stories.",
    "whyPeopleBelieveIt": "A Federal Register doc feels like the main story because it is dated and quotable.",
    "howToSpotIt": "Ask what else moved the same day on tracker, Congress, FOIA, and dockets.",
    "severity": 6,
    "categories": [
      "Economy",
      "Environment"
    ],
    "sources": [
      {
        "id": "fr_dist_2026_14654",
        "title": "Action by the United States in the Investigation Under Section 301 of the Trade Act of 1974 of Brazil's Acts, Policies, and Practices Related to Digital Trade and Electronic Payment Services; Unfair, Preferential Tariffs; Anti-Corruption Enforcement; Intellectual Property Protection; Ethanol Market Access; and Illegal Deforestation",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/20/2026-14654/action-by-the-united-states-in-the-investigation-under-section-301-of-the-trade-act-of-1974-of",
        "waybackUrl": "https://web.archive.org/web/*/https://www.federalregister.gov/documents/2026/07/20/2026-14654/action-by-the-united-states-in-the-investigation-under-section-301-of-the-trade-act-of-1974-of",
        "excerpt": "Federal Register presidential document - auto-stub pending editorial pass.",
        "date": "2026-07-20"
      }
    ]
  },
  {
    "id": "DIST-AUTO-20260716-2026-14454",
    "date": "2026-07-16",
    "title": "Continuation of the National Emergency With Respect to Significant Transnational Criminal Organizations",
    "distraction": "Official FR spotlight: Continuation of the National Emergency With Respect to Significant Transnational Criminal Organizations",
    "coveringUp": "Same-day tracker severity, disclosure fights, or floor votes this may bury.",
    "whyTheyDoIt": "A fresh official action steals oxygen from accountability stories.",
    "whyPeopleBelieveIt": "A Federal Register doc feels like the main story because it is dated and quotable.",
    "howToSpotIt": "Ask what else moved the same day on tracker, Congress, FOIA, and dockets.",
    "severity": 7,
    "categories": [
      "News Cycle"
    ],
    "sources": [
      {
        "id": "fr_dist_2026_14454",
        "title": "Continuation of the National Emergency With Respect to Significant Transnational Criminal Organizations",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/16/2026-14454/continuation-of-the-national-emergency-with-respect-to-significant-transnational-criminal",
        "waybackUrl": "https://web.archive.org/web/*/https://www.federalregister.gov/documents/2026/07/16/2026-14454/continuation-of-the-national-emergency-with-respect-to-significant-transnational-criminal",
        "excerpt": "Federal Register presidential document - auto-stub pending editorial pass.",
        "date": "2026-07-16"
      }
    ]
  },
  {
    "id": "DIST-AUTO-20260716-2026-14453",
    "date": "2026-07-16",
    "title": "Continuation of the National Emergency With Respect to Hostage-Taking and the Wrongful Detention of United States Nationals Abroad",
    "distraction": "Official FR spotlight: Continuation of the National Emergency With Respect to Hostage-Taking and the Wrongful…",
    "coveringUp": "Same-day tracker severity, disclosure fights, or floor votes this may bury.",
    "whyTheyDoIt": "A fresh official action steals oxygen from accountability stories.",
    "whyPeopleBelieveIt": "A Federal Register doc feels like the main story because it is dated and quotable.",
    "howToSpotIt": "Ask what else moved the same day on tracker, Congress, FOIA, and dockets.",
    "severity": 7,
    "categories": [
      "News Cycle"
    ],
    "sources": [
      {
        "id": "fr_dist_2026_14453",
        "title": "Continuation of the National Emergency With Respect to Hostage-Taking and the Wrongful Detention of United States Nationals Abroad",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/16/2026-14453/continuation-of-the-national-emergency-with-respect-to-hostage-taking-and-the-wrongful-detention-of",
        "waybackUrl": "https://web.archive.org/web/*/https://www.federalregister.gov/documents/2026/07/16/2026-14453/continuation-of-the-national-emergency-with-respect-to-hostage-taking-and-the-wrongful-detention-of",
        "excerpt": "Federal Register presidential document - auto-stub pending editorial pass.",
        "date": "2026-07-16"
      }
    ]
  },
  {
    "id": "DIST-AUTO-20260706-2026-13631",
    "date": "2026-07-06",
    "title": "Presidential Determination on Assistance to Venezuela Consistent With the Trafficking Victims Protection Act of 2000",
    "distraction": "Official FR spotlight: Presidential Determination on Assistance to Venezuela Consistent With the Trafficking Victims Protection…",
    "coveringUp": "Same-day tracker severity, disclosure fights, or floor votes this may bury.",
    "whyTheyDoIt": "A fresh official action steals oxygen from accountability stories.",
    "whyPeopleBelieveIt": "A Federal Register doc feels like the main story because it is dated and quotable.",
    "howToSpotIt": "Ask what else moved the same day on tracker, Congress, FOIA, and dockets.",
    "severity": 5,
    "categories": [
      "News Cycle"
    ],
    "sources": [
      {
        "id": "fr_dist_2026_13631",
        "title": "Presidential Determination on Assistance to Venezuela Consistent With the Trafficking Victims Protection Act of 2000",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/06/2026-13631/presidential-determination-on-assistance-to-venezuela-consistent-with-the-trafficking-victims",
        "waybackUrl": "https://web.archive.org/web/*/https://www.federalregister.gov/documents/2026/07/06/2026-13631/presidential-determination-on-assistance-to-venezuela-consistent-with-the-trafficking-victims",
        "excerpt": "Federal Register presidential document - auto-stub pending editorial pass.",
        "date": "2026-07-06"
      }
    ]
  },
  {
    "id": "DIST-AUTO-20260702-2026-13588",
    "date": "2026-07-02",
    "title": "Declaration of Emergency and Authorization for Temporary Duty-Free Importation of Phosphate Fertilizer From Morocco",
    "distraction": "Official FR spotlight: Declaration of Emergency and Authorization for Temporary Duty-Free Importation of Phosphate Fertilizer…",
    "coveringUp": "Same-day tracker severity, disclosure fights, or floor votes this may bury.",
    "whyTheyDoIt": "A fresh official action steals oxygen from accountability stories.",
    "whyPeopleBelieveIt": "A Federal Register doc feels like the main story because it is dated and quotable.",
    "howToSpotIt": "Ask what else moved the same day on tracker, Congress, FOIA, and dockets.",
    "severity": 7,
    "categories": [
      "News Cycle"
    ],
    "sources": [
      {
        "id": "fr_dist_2026_13588",
        "title": "Declaration of Emergency and Authorization for Temporary Duty-Free Importation of Phosphate Fertilizer From Morocco",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/02/2026-13588/declaration-of-emergency-and-authorization-for-temporary-duty-free-importation-of-phosphate",
        "waybackUrl": "https://web.archive.org/web/*/https://www.federalregister.gov/documents/2026/07/02/2026-13588/declaration-of-emergency-and-authorization-for-temporary-duty-free-importation-of-phosphate",
        "excerpt": "Federal Register presidential document - auto-stub pending editorial pass.",
        "date": "2026-07-02"
      }
    ]
  },
  {
    "id": "DIST-AUTO-20260701-2026-13408",
    "date": "2026-07-01",
    "title": "Presidential Determination Concerning the Department of the Air Force's Rehabilitation and Revitalization of the Joint Base Andrews Golf Course",
    "distraction": "Official FR spotlight: Presidential Determination Concerning the Department of the Air Force's Rehabilitation and Revitalization…",
    "coveringUp": "Same-day tracker severity, disclosure fights, or floor votes this may bury.",
    "whyTheyDoIt": "A fresh official action steals oxygen from accountability stories.",
    "whyPeopleBelieveIt": "A Federal Register doc feels like the main story because it is dated and quotable.",
    "howToSpotIt": "Ask what else moved the same day on tracker, Congress, FOIA, and dockets.",
    "severity": 5,
    "categories": [
      "Environment"
    ],
    "sources": [
      {
        "id": "fr_dist_2026_13408",
        "title": "Presidential Determination Concerning the Department of the Air Force's Rehabilitation and Revitalization of the Joint Base Andrews Golf Course",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/01/2026-13408/presidential-determination-concerning-the-department-of-the-air-forces-rehabilitation-and",
        "waybackUrl": "https://web.archive.org/web/*/https://www.federalregister.gov/documents/2026/07/01/2026-13408/presidential-determination-concerning-the-department-of-the-air-forces-rehabilitation-and",
        "excerpt": "Federal Register presidential document - auto-stub pending editorial pass.",
        "date": "2026-07-01"
      }
    ]
  }
] as DistractionEntry[];

export const autoDistractedMeta = {
  "generatedAt": "2026-07-20T14:00:32.598Z",
  "lookbackDays": 21,
  "frFetched": 13,
  "frCandidates": 6,
  "rssFetched": 10,
  "congressCount": 0,
  "newlyAddedCount": 0,
  "autoEntryCount": 6,
  "curatedIdCount": 48
} as const;
