/**
 * Auto-ingested tracker events from Federal Register (and related public feeds).
 * Regenerated by: npm run refresh:tracker (scripts/update-tracker-data.ts)
 *
 * Do not hand-edit  -  curated narrative events live in timeline-events.ts.
 */
import type { TimelineEvent } from "@/lib/types";

export const autoTimelineEvents: TimelineEvent[] = [
  {
    "Event_ID": "EVT-AUTO-20260708-26-13842",
    "Date": "2026-07-08",
    "Action_Type": "Presidential Document",
    "Description": "250th Anniversary of the Adoption of the Declaration of Independence  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_13842",
        "title": "250th Anniversary of the Adoption of the Declaration of Independence",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/08/2026-13842/250th-anniversary-of-the-adoption-of-the-declaration-of-independence",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/07/08/2026-13842/250th-anniversary-of-the-adoption-of-the-declaration-of-independence",
        "excerpt": "Presidential Document published in the Federal Register (2026-13842). Auto-ingested pending editorial pass.",
        "date": "2026-07-08"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260706-26-13631",
    "Date": "2026-07-06",
    "Action_Type": "Presidential Document",
    "Description": "Presidential Determination on Assistance to Venezuela Consistent With the Trafficking Victims Protection Act of 2000  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_13631",
        "title": "Presidential Determination on Assistance to Venezuela Consistent With the Trafficking Victims Protection Act of 2000",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/06/2026-13631/presidential-determination-on-assistance-to-venezuela-consistent-with-the-trafficking-victims",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/07/06/2026-13631/presidential-determination-on-assistance-to-venezuela-consistent-with-the-trafficking-victims",
        "excerpt": "Presidential Document published in the Federal Register (2026-13631). Auto-ingested pending editorial pass.",
        "date": "2026-07-06"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260702-26-13588",
    "Date": "2026-07-02",
    "Action_Type": "Presidential Document",
    "Description": "Declaration of Emergency and Authorization for Temporary Duty-Free Importation of Phosphate Fertilizer From Morocco  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 7,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_13588",
        "title": "Declaration of Emergency and Authorization for Temporary Duty-Free Importation of Phosphate Fertilizer From Morocco",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/02/2026-13588/declaration-of-emergency-and-authorization-for-temporary-duty-free-importation-of-phosphate",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/07/02/2026-13588/declaration-of-emergency-and-authorization-for-temporary-duty-free-importation-of-phosphate",
        "excerpt": "Presidential Document published in the Federal Register (2026-13588). Auto-ingested pending editorial pass.",
        "date": "2026-07-02"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260701-26-13408",
    "Date": "2026-07-01",
    "Action_Type": "Presidential Document",
    "Description": "Presidential Determination Concerning the Department of the Air Force's Rehabilitation and Revitalization of the Joint Base Andrews Golf Course  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Environment"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_13408",
        "title": "Presidential Determination Concerning the Department of the Air Force's Rehabilitation and Revitalization of the Joint Base Andrews Golf Course",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/07/01/2026-13408/presidential-determination-concerning-the-department-of-the-air-forces-rehabilitation-and",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/07/01/2026-13408/presidential-determination-concerning-the-department-of-the-air-forces-rehabilitation-and",
        "excerpt": "Presidential Document published in the Federal Register (2026-13408). Auto-ingested pending editorial pass.",
        "date": "2026-07-01"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Environment",
    "p2025Pillar": "Energy & Environment",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260630-26-13254",
    "Date": "2026-06-30",
    "Action_Type": "Presidential Document",
    "Description": "Advancing Regenerative Agriculture and Strengthening American Farm Resilience  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_13254",
        "title": "Advancing Regenerative Agriculture and Strengthening American Farm Resilience",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/30/2026-13254/advancing-regenerative-agriculture-and-strengthening-american-farm-resilience",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/30/2026-13254/advancing-regenerative-agriculture-and-strengthening-american-farm-resilience",
        "excerpt": "Presidential Document published in the Federal Register (2026-13254). Auto-ingested pending editorial pass.",
        "date": "2026-06-30"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260625-26-12910",
    "Date": "2026-06-25",
    "Action_Type": "Presidential Document",
    "Description": "Ushering in the Next Frontier of Quantum Innovation  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12910",
        "title": "Ushering in the Next Frontier of Quantum Innovation",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/25/2026-12910/ushering-in-the-next-frontier-of-quantum-innovation",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/25/2026-12910/ushering-in-the-next-frontier-of-quantum-innovation",
        "excerpt": "Presidential Document published in the Federal Register (2026-12910). Auto-ingested pending editorial pass.",
        "date": "2026-06-25"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260625-26-12909",
    "Date": "2026-06-25",
    "Action_Type": "Presidential Document",
    "Description": "Securing the Nation Against Advanced Cryptographic Attacks  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12909",
        "title": "Securing the Nation Against Advanced Cryptographic Attacks",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/25/2026-12909/securing-the-nation-against-advanced-cryptographic-attacks",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/25/2026-12909/securing-the-nation-against-advanced-cryptographic-attacks",
        "excerpt": "Presidential Document published in the Federal Register (2026-12909). Auto-ingested pending editorial pass.",
        "date": "2026-06-25"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260624-26-12837",
    "Date": "2026-06-24",
    "Action_Type": "Presidential Document",
    "Description": "Continuation of the National Emergency With Respect to the Western Balkans  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 7,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12837",
        "title": "Continuation of the National Emergency With Respect to the Western Balkans",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/24/2026-12837/continuation-of-the-national-emergency-with-respect-to-the-western-balkans",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/24/2026-12837/continuation-of-the-national-emergency-with-respect-to-the-western-balkans",
        "excerpt": "Presidential Document published in the Federal Register (2026-12837). Auto-ingested pending editorial pass.",
        "date": "2026-06-24"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260624-26-12836",
    "Date": "2026-06-24",
    "Action_Type": "Presidential Document",
    "Description": "Continuation of the National Emergency With Respect to North Korea  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 7,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12836",
        "title": "Continuation of the National Emergency With Respect to North Korea",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/24/2026-12836/continuation-of-the-national-emergency-with-respect-to-north-korea",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/24/2026-12836/continuation-of-the-national-emergency-with-respect-to-north-korea",
        "excerpt": "Presidential Document published in the Federal Register (2026-12836). Auto-ingested pending editorial pass.",
        "date": "2026-06-24"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260618-26-12436",
    "Date": "2026-06-18",
    "Action_Type": "Presidential Document",
    "Description": "Flag Day and National Flag Week, 2026  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 3,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12436",
        "title": "Flag Day and National Flag Week, 2026",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/18/2026-12436/flag-day-and-national-flag-week-2026",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/18/2026-12436/flag-day-and-national-flag-week-2026",
        "excerpt": "Presidential Document published in the Federal Register (2026-12436). Auto-ingested pending editorial pass.",
        "date": "2026-06-18"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260617-26-12286",
    "Date": "2026-06-17",
    "Action_Type": "Presidential Document",
    "Description": "Presidential Determination and Delegation of Authority Under Section 708 of the Defense Production Act of 1950, as Amended  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12286",
        "title": "Presidential Determination and Delegation of Authority Under Section 708 of the Defense Production Act of 1950, as Amended",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/17/2026-12286/presidential-determination-and-delegation-of-authority-under-section-708-of-the-defense-production",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/17/2026-12286/presidential-determination-and-delegation-of-authority-under-section-708-of-the-defense-production",
        "excerpt": "Presidential Document published in the Federal Register (2026-12286). Auto-ingested pending editorial pass.",
        "date": "2026-06-17"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260617-26-12283",
    "Date": "2026-06-17",
    "Action_Type": "Presidential Document",
    "Description": "Restoring American Commercial Fishing in the Pacific  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12283",
        "title": "Restoring American Commercial Fishing in the Pacific",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/17/2026-12283/restoring-american-commercial-fishing-in-the-pacific",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/17/2026-12283/restoring-american-commercial-fishing-in-the-pacific",
        "excerpt": "Presidential Document published in the Federal Register (2026-12283). Auto-ingested pending editorial pass.",
        "date": "2026-06-17"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260617-26-12282",
    "Date": "2026-06-17",
    "Action_Type": "Presidential Document",
    "Description": "75th Anniversary of the White House Navy Mess, 2026  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_12282",
        "title": "75th Anniversary of the White House Navy Mess, 2026",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/17/2026-12282/75th-anniversary-of-the-white-house-navy-mess-2026",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/17/2026-12282/75th-anniversary-of-the-white-house-navy-mess-2026",
        "excerpt": "Presidential Document published in the Federal Register (2026-12282). Auto-ingested pending editorial pass.",
        "date": "2026-06-17"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260610-26-11741",
    "Date": "2026-06-10",
    "Action_Type": "Presidential Document",
    "Description": "Granting Pardon to Stephen E. Buyer  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_11741",
        "title": "Granting Pardon to Stephen E. Buyer",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/10/2026-11741/granting-pardon-to-stephen-e-buyer",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/10/2026-11741/granting-pardon-to-stephen-e-buyer",
        "excerpt": "Presidential Document published in the Federal Register (2026-11741). Auto-ingested pending editorial pass.",
        "date": "2026-06-10"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260610-26-11595",
    "Date": "2026-06-10",
    "Action_Type": "Presidential Document",
    "Description": "Strengthening Customs Enforcement  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Immigration"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_11595",
        "title": "Strengthening Customs Enforcement",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/10/2026-11595/strengthening-customs-enforcement",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/10/2026-11595/strengthening-customs-enforcement",
        "excerpt": "Presidential Document published in the Federal Register (2026-11595). Auto-ingested pending editorial pass.",
        "date": "2026-06-10"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Immigration",
    "p2025Pillar": "Immigration Enforcement",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260610-26-11594",
    "Date": "2026-06-10",
    "Action_Type": "Presidential Document",
    "Description": "Implementing Schedule Policy/Career in the Excepted Service  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 7,
    "Impacted_Sectors": [
      "Civil Rights"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_11594",
        "title": "Implementing Schedule Policy/Career in the Excepted Service",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/10/2026-11594/implementing-schedule-policycareer-in-the-excepted-service",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/10/2026-11594/implementing-schedule-policycareer-in-the-excepted-service",
        "excerpt": "Presidential Document published in the Federal Register (2026-11594). Auto-ingested pending editorial pass.",
        "date": "2026-06-10"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Civil Rights",
    "p2025Pillar": "Personnel & Civil Service",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260603-26-11181",
    "Date": "2026-06-03",
    "Action_Type": "Presidential Document",
    "Description": "Removing Unnecessary and Counterproductive Restrictions on Access to Federal Lands  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Environment"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_11181",
        "title": "Removing Unnecessary and Counterproductive Restrictions on Access to Federal Lands",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/03/2026-11181/removing-unnecessary-and-counterproductive-restrictions-on-access-to-federal-lands",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/03/2026-11181/removing-unnecessary-and-counterproductive-restrictions-on-access-to-federal-lands",
        "excerpt": "Presidential Document published in the Federal Register (2026-11181). Auto-ingested pending editorial pass.",
        "date": "2026-06-03"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Environment",
    "p2025Pillar": "Energy & Environment",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  },
  {
    "Event_ID": "EVT-AUTO-20260603-26-11180",
    "Date": "2026-06-03",
    "Action_Type": "Presidential Document",
    "Description": "Realigning United States Core Childhood Vaccine Recommendations With Best Practices From Peer, Developed Countries  -  auto-ingested from Federal Register; severity and narrative pending editorial review.",
    "Severity_Score": 5,
    "Impacted_Sectors": [
      "Democracy"
    ],
    "Sources": [
      {
        "id": "fr_auto_2026_11180",
        "title": "Realigning United States Core Childhood Vaccine Recommendations With Best Practices From Peer, Developed Countries",
        "publisher": "Federal Register",
        "url": "https://www.federalregister.gov/documents/2026/06/03/2026-11180/realigning-united-states-core-childhood-vaccine-recommendations-with-best-practices-from-peer",
        "waybackUrl": "https://web.archive.org/web/https://www.federalregister.gov/documents/2026/06/03/2026-11180/realigning-united-states-core-childhood-vaccine-recommendations-with-best-practices-from-peer",
        "excerpt": "Presidential Document published in the Federal Register (2026-11180). Auto-ingested pending editorial pass.",
        "date": "2026-06-03"
      }
    ],
    "Linked_Fix_ID": null,
    "category": "Democracy",
    "p2025Pillar": "Executive Authority",
    "externalTrackers": [
      {
        "name": "project2025.observer",
        "url": "https://www.project2025.observer/"
      },
      {
        "name": "CPR Executive Action Tracker",
        "url": "https://progressivereform.org/tracking-trump-2/project-2025-executive-action-tracker/"
      }
    ]
  }
] as TimelineEvent[];

export const autoTrackerMeta = {
  "generatedAt": "2026-07-13T15:48:07.213Z",
  "source": "federalregister.gov",
  "president": "donald-trump",
  "lookbackDays": 45,
  "fetchedCount": 21,
  "notInCurated": 18,
  "newlyAddedCount": 18,
  "autoEventCount": 18,
  "observer": {
    "ok": true,
    "status": 200,
    "note": "Reachable (no public JSON API; used as external cross-ref only)"
  }
} as const;
