/**
 * Auto-ingested tracker events from Federal Register (and related public feeds).
 * Regenerated by: npm run refresh:tracker (scripts/update-tracker-data.ts)
 *
 * Do not hand-edit — curated narrative events live in timeline-events.ts.
 */
import type { TimelineEvent } from "@/lib/types";

export const autoTimelineEvents: TimelineEvent[] = [] as TimelineEvent[];

export const autoTrackerMeta = {
  "generatedAt": "2026-07-20T15:30:27.635Z",
  "source": "federalregister.gov",
  "president": "donald-trump",
  "lookbackDays": 45,
  "frAutoEnabled": false,
  "maxTitleChars": 120,
  "fetchedCount": 0,
  "notInCurated": 0,
  "newlyAddedCount": 0,
  "autoEventCount": 0,
  "observer": {
    "ok": true,
    "status": 200,
    "note": "Reachable (no public JSON API; used as external cross-ref only)"
  },
  "note": "Curated-only: FR→tracker auto disabled (TRACKER_FR_AUTO!=1)"
} as const;
