/**
 * Pass 26 content applicator - expands history, rebuttals, tracker, blueprint, meta pages.
 * Run: node scripts/pass26/apply.mjs
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "../..");
const data = (f) => join(ROOT, "lib", "data", f);

function insertBefore(file, marker, content) {
  let src = readFileSync(file, "utf8");
  if (!src.includes(marker)) throw new Error(`Marker not found in ${file}: ${marker}`);
  if (src.includes("Pass 26 expansions") || src.includes("PASS26_MARKER")) {
    console.log("skip already applied?", file);
  }
  src = src.replace(marker, content + "\n" + marker);
  writeFileSync(file, src);
  console.log("patched", file);
}

const historyCitations = `
  // Pass 26 expansions
  trail_of_tears: c("trail_of_tears", "Trail of Tears", "National Park Service", "https://www.nps.gov/trte/learn/historyculture/index.htm", "Forced Cherokee removal killed thousands on the march west under the Indian Removal Act.", "1838-01-01"),
  nat_turner: c("nat_turner", "Nat Turner's Rebellion", "National Park Service", "https://www.nps.gov/articles/nat-turner.htm", "The 1831 uprising led to harsher slave codes and bans on Black literacy across the South.", "1831-08-21"),
  mexican_american_war: c("mexican_american_war", "Mexican-American War", "U.S. Department of State", "https://history.state.gov/milestones/1830-1860/texas-annexation", "U.S. annexation of Texas and war with Mexico seized roughly half of Mexico's territory.", "1846-05-13"),
  dawes_act: c("dawes_act", "Dawes Act", "National Archives", "https://www.archives.gov/milestone-documents/dawes-act", "The 1887 allotment law broke up tribal lands and transferred millions of acres to settlers.", "1887-02-08"),
  wilmington_1898: c("wilmington_1898", "Wilmington Massacre of 1898", "Wikipedia", "https://en.wikipedia.org/wiki/Wilmington_massacre", "White supremacists overthrew a biracial government and killed dozens of Black residents.", "1898-11-10"),
  convict_leasing: c("convict_leasing", "Convict leasing", "Wikipedia", "https://en.wikipedia.org/wiki/Convict_leasing", "The 13th Amendment's punishment clause enabled forced Black labor through criminalization.", "1866-01-01"),
  buck_v_bell: c("buck_v_bell", "Buck v. Bell", "Wikipedia", "https://en.wikipedia.org/wiki/Buck_v._Bell", "The Court upheld compulsory sterilization of people labeled feeble-minded in 1927.", "1927-05-02"),
  scottsboro: c("scottsboro", "Scottsboro Boys", "National Museum of African American History and Culture", "https://nmaahc.si.edu/explore/stories/scottsboro-boys", "Nine Black teens faced death sentences on false rape charges; the case exposed Jim Crow justice.", "1931-03-25"),
  mexican_repatriation: c("mexican_repatriation", "Mexican Repatriation", "Wikipedia", "https://en.wikipedia.org/wiki/Mexican_Repatriation", "1930s mass removals forced hundreds of thousands of Mexican Americans, many U.S. citizens, out of the country.", "1931-01-01"),
  zoot_suit: c("zoot_suit", "Zoot Suit Riots", "Wikipedia", "https://en.wikipedia.org/wiki/Zoot_Suit_Riots", "Sailors and police attacked Mexican American youth in Los Angeles in 1943.", "1943-06-03"),
  church_committee: c("church_committee", "Church Committee", "U.S. Senate Select Committee on Intelligence", "https://www.intelligence.senate.gov/publications/church-committee-reports/", "1975 Senate investigation documented COINTELPRO, assassination plots, and illegal surveillance.", "1975-01-01"),
  love_canal: c("love_canal", "Love Canal", "Environmental Protection Agency", "https://www.epa.gov/archive/epa/aboutepa/love-canal-tragedy.html", "Toxic waste buried under a Niagara Falls neighborhood sparked Superfund and environmental justice organizing.", "1978-08-07"),
  patco_strike: c("patco_strike", "Professional Air Traffic Controllers Organization", "Wikipedia", "https://en.wikipedia.org/wiki/Professional_Air_Traffic_Controllers_Organization_(1968)", "Reagan fired over 11,000 striking air traffic controllers in 1981, accelerating union decline.", "1981-08-05"),
  fairness_doctrine: c("fairness_doctrine", "FCC fairness doctrine", "Wikipedia", "https://en.wikipedia.org/wiki/FCC_fairness_doctrine", "The FCC repealed the Fairness Doctrine in 1987, ending broadcast balance requirements.", "1987-08-04"),
  ada_1990: c("ada_1990", "Americans with Disabilities Act", "National Archives", "https://www.archives.gov/milestone-documents/americans-with-disabilities-act", "The 1990 ADA banned disability discrimination in employment, public services, and accommodations.", "1990-07-26"),
  section_504: c("section_504", "504 Sit-in", "Wikipedia", "https://en.wikipedia.org/wiki/504_Sit-in", "Disability activists occupied federal buildings in 1977 until Section 504 regulations were signed.", "1977-04-05"),
  shelby_county: c("shelby_county", "Shelby County v. Holder", "Brennan Center for Justice", "https://www.brennancenter.org/our-work/research-reports/shelby-county-v-holder", "The 2013 ruling gutted Voting Rights Act preclearance; states immediately passed restrictive voting laws.", "2013-06-25"),
  flint_water: c("flint_water", "Flint water crisis", "Wikipedia", "https://en.wikipedia.org/wiki/Flint_water_crisis", "Lead-contaminated water poisoned Flint residents after cost-cutting switched the water source.", "2014-04-25"),
  obergefell: c("obergefell", "Obergefell v. Hodges", "Oyez", "https://www.oyez.org/cases/2014/14-556", "The Court recognized a constitutional right to same-sex marriage in 2015.", "2015-06-26"),
  citizenship_1924: c("citizenship_1924", "Indian Citizenship Act", "National Archives", "https://www.archives.gov/milestone-documents/indian-citizenship-act", "The 1924 act granted citizenship to Native Americans while many states still blocked their voting.", "1924-06-02"),
  red_summer: c("red_summer", "Red Summer", "National Archives", "https://www.archives.gov/research/african-americans/wwi/red-summer", "White mobs attacked Black communities across dozens of cities in 1919.", "1919-07-01"),
  palmer_raids: c("palmer_raids", "Palmer Raids", "National Archives", "https://www.archives.gov/publications/prologue/2019/winter/palmer-raids", "Attorney General Palmer's 1919-20 raids deported radicals without due process.", "1919-11-07"),
  gi_bill_exclusion: c("gi_bill_exclusion", "Servicemen's Readjustment Act", "National Archives", "https://www.archives.gov/milestone-documents/servicemens-readjustment-act", "The G.I. Bill built white middle-class wealth while local administration often excluded Black veterans.", "1944-06-22"),
  brazil_coup_1964: c("brazil_coup_1964", "1964 Brazilian coup d'état", "Wikipedia", "https://en.wikipedia.org/wiki/1964_Brazilian_coup_d%27%C3%A9tat", "The U.S. backed the military overthrow of Brazil's elected government.", "1964-04-01"),
  pentagon_papers: c("pentagon_papers", "Pentagon Papers", "National Archives", "https://www.archives.gov/research/pentagon-papers", "Leaked DoD study showed successive administrations lied about Vietnam escalation.", "1971-06-13"),
  war_on_drugs: c("war_on_drugs", "War on drugs", "Wikipedia", "https://en.wikipedia.org/wiki/War_on_drugs", "Nixon-era drug war policies drove mass incarceration disproportionately targeting Black communities.", "1971-06-17"),
  katrina: c("katrina", "Hurricane Katrina", "Wikipedia", "https://en.wikipedia.org/wiki/Hurricane_Katrina", "Failed levees and slow federal response devastated New Orleans's Black neighborhoods in 2005.", "2005-08-29"),
  citizens_united_hist: c("citizens_united_hist", "Citizens United v. FEC", "Oyez", "https://www.oyez.org/cases/2008/08-205", "The 2010 decision allowed unlimited independent political spending by corporations and unions.", "2010-01-21"),
  snowden_prism: c("snowden_prism", "PRISM (surveillance program)", "Wikipedia", "https://en.wikipedia.org/wiki/PRISM", "Snowden disclosures revealed mass NSA surveillance of Americans after COINTELPRO-era reforms.", "2013-06-06"),
  dobbs: c("dobbs", "Dobbs v. Jackson Women's Health Organization", "Oyez", "https://www.oyez.org/cases/2021/19-1392", "The 2022 decision overturned Roe v. Wade and ended federal abortion rights.", "2022-06-24"),
  alien_sedition: c("alien_sedition", "Alien and Sedition Acts", "National Archives", "https://www.archives.gov/milestone-documents/alien-and-sedition-acts", "1798 laws criminalized criticism of the federal government and targeted immigrants.", "1798-07-14"),
  stono: c("stono", "Stono Rebellion", "National Park Service", "https://www.nps.gov/articles/stono-rebellion.htm", "The 1739 South Carolina uprising led to harsher slave codes banning literacy and assembly.", "1739-09-09"),
  bacon_rebellion: c("bacon_rebellion", "Bacon's Rebellion", "National Park Service", "https://www.nps.gov/jame/learn/historyculture/bacons-rebellion.htm", "After 1676, elites hardened race-based slavery to divide poor whites from Black laborers.", "1676-01-01"),
  immigration_1924: c("immigration_1924", "Immigration Act of 1924", "Office of the Historian", "https://history.state.gov/milestones/1921-1936/immigration-act", "National-origin quotas locked in white European preference and barred Asian immigration.", "1924-05-26"),
  bracero: c("bracero", "Bracero Program", "National Archives", "https://www.archives.gov/research/hispanic/bracero", "Wartime guest-worker program imported Mexican labor under exploitative contracts.", "1942-08-04"),
  operation_wetback: c("operation_wetback", "Operation Wetback", "Wikipedia", "https://en.wikipedia.org/wiki/Operation_Wetback", "1954 mass deportation campaign swept up U.S. citizens and legal residents of Mexican descent.", "1954-06-17"),
  creel_committee: c("creel_committee", "Committee on Public Information", "Wikipedia", "https://en.wikipedia.org/wiki/Committee_on_Public_Information", "Wilson's WWI propaganda agency pioneered modern government information warfare.", "1917-04-13"),
  willowbrook: c("willowbrook", "Willowbrook State School", "Wikipedia", "https://en.wikipedia.org/wiki/Willowbrook_State_School", "Investigations exposed abuse and medical experiments on disabled children in New York.", "1972-01-01"),
  cancer_alley: c("cancer_alley", "Cancer Alley", "Wikipedia", "https://en.wikipedia.org/wiki/Cancer_Alley", "Petrochemical corridor along the Mississippi disproportionately burdens Black Louisiana communities.", "1987-01-01"),
  voting_rights_1965: c("voting_rights_1965", "Voting Rights Act of 1965", "National Archives", "https://www.archives.gov/milestone-documents/voting-rights-act", "The VRA banned literacy tests and required federal preclearance for discriminatory voting changes.", "1965-08-06"),
  grenada_1983: c("grenada_1983", "Invasion of Grenada", "Wikipedia", "https://en.wikipedia.org/wiki/Invasion_of_Grenada", "The U.S. invaded Grenada in 1983, overthrowing its government without UN authorization.", "1983-10-25"),
  family_separation: c("family_separation", "Trump administration family separation policy", "Wikipedia", "https://en.wikipedia.org/wiki/Trump_administration_family_separation_policy", "Zero-tolerance prosecution intentionally separated thousands of migrant children from parents.", "2018-04-06"),
  charlottesville: c("charlottesville", "Unite the Right rally", "Wikipedia", "https://en.wikipedia.org/wiki/Unite_the_Right_rally", "Neo-Nazis and white nationalists marched in 2017; a counter-protester was murdered.", "2017-08-12"),
  floyd_2020: c("floyd_2020", "George Floyd protests", "Wikipedia", "https://en.wikipedia.org/wiki/George_Floyd_protests", "Police murder of George Floyd sparked the largest civil rights protests in U.S. history.", "2020-05-25"),
  pulse_orlando: c("pulse_orlando", "Pulse nightclub shooting", "Wikipedia", "https://en.wikipedia.org/wiki/Pulse_nightclub_shooting", "A gunman killed 49 people at a LGBTQ nightclub in Orlando in 2016.", "2016-06-12"),
  bisbee: c("bisbee", "Bisbee Deportation", "Wikipedia", "https://en.wikipedia.org/wiki/Bisbee_Deportation", "In 1917, armed deputies kidnapped and deported over 1,000 striking miners from Arizona.", "1917-07-12"),
  memorial_day_massacre: c("memorial_day_massacre", "Memorial Day massacre of 1937", "Wikipedia", "https://en.wikipedia.org/wiki/Memorial_Day_massacre_of_1937", "Chicago police killed 10 unarmed steel strikers and wounded dozens on Memorial Day 1937.", "1937-05-30"),
  gnadenhutten: c("gnadenhutten", "Gnadenhutten massacre", "Wikipedia", "https://en.wikipedia.org/wiki/Gnadenhutten_massacre", "Militia murdered 96 Christian Lenape civilians in Ohio in 1782.", "1782-03-08"),
  king_philips_war: c("king_philips_war", "King Philip's War", "National Park Service", "https://www.nps.gov/articles/000/king-philip-s-war.htm", "1675-76 war devastated New England Native nations and opened land for English settlers.", "1675-06-20"),
  operation_condor: c("operation_condor", "Operation Condor", "Wikipedia", "https://en.wikipedia.org/wiki/Operation_Condor", "South American dictatorships coordinated disappearances with U.S. knowledge and support.", "1975-01-01"),
  three_mile_island: c("three_mile_island", "Three Mile Island accident", "Nuclear Regulatory Commission", "https://www.nrc.gov/reading-rm/doc-collections/fact-sheets/3mile-isle.html", "The 1979 partial meltdown exposed nuclear risk and eroded public trust in industry assurances.", "1979-03-28"),
  welfare_reform_1996: c("welfare_reform_1996", "Personal Responsibility and Work Opportunity Reconciliation Act", "Congress.gov", "https://www.congress.gov/bill/104th-congress/house-bill/3734", "1996 welfare reform ended AFDC entitlement and imposed time limits that deepened poverty for many families.", "1996-08-22"),
  lawrence_v_texas: c("lawrence_v_texas", "Lawrence v. Texas", "Wikipedia", "https://en.wikipedia.org/wiki/Lawrence_v._Texas", "The 2003 ruling struck down sodomy laws criminalizing same-sex intimacy.", "2003-06-26"),
  bowers_v_hardwick: c("bowers_v_hardwick", "Bowers v. Hardwick", "Wikipedia", "https://en.wikipedia.org/wiki/Bowers_v._Hardwick", "The 1986 Court upheld criminalization of private same-sex intimacy until Lawrence overturned it.", "1986-06-30"),
  indian_reorg: c("indian_reorg", "Indian Reorganization Act", "Bureau of Indian Affairs", "https://www.bia.gov/as-ia/opa/online-press-release/indian-reorganization-act-80th-anniversary", "1934 IRA ended allotment but imposed federal templates that still constrained tribal sovereignty.", "1934-06-18"),
  wounded_knee_1973: c("wounded_knee_1973", "Wounded Knee Occupation", "Wikipedia", "https://en.wikipedia.org/wiki/Wounded_Knee_Occupation", "AIM occupied Wounded Knee in 1973 to protest treaty violations and tribal corruption.", "1973-02-27"),
  mass_incarceration_bjs: c("mass_incarceration_bjs", "Correctional Populations in the United States", "Bureau of Justice Statistics", "https://bjs.ojp.gov/", "U.S. incarceration rates remain among the world's highest, shaped by drug-war sentencing.", "2022-01-01"),
  nafta_labor: c("nafta_labor", "The North American Free Trade Agreement (NAFTA)", "Congressional Research Service", "https://crsreports.congress.gov/product/pdf/R/R42965", "NAFTA accelerated manufacturing offshoring and weakened U.S. industrial bargaining power.", "1994-01-01"),
  rodney_king: c("rodney_king", "1992 Los Angeles riots", "Wikipedia", "https://en.wikipedia.org/wiki/1992_Los_Angeles_riots", "Acquittal of officers who beat Rodney King triggered uprising against police violence.", "1992-04-29"),
  chinese_massacre_1871: c("chinese_massacre_1871", "Chinese massacre of 1871", "Wikipedia", "https://en.wikipedia.org/wiki/Chinese_massacre_of_1871", "A Los Angeles mob lynched 18 Chinese immigrants in one of the largest mass lynchings in U.S. history.", "1871-10-24"),
`;

function entry(id, date, sortYear, era, title, textbook, actual, rebuttals, sources, categories, related) {
  const reb = rebuttals.map(([they, you, srcs]) =>
    `      { theySaid: ${JSON.stringify(they)}, youSay: ${JSON.stringify(you)}, sources: [${srcs.map(s=>`h.${s}`).join(", ")}] },`
  ).join("\n");
  return `  {
    id: ${JSON.stringify(id)},
    date: ${JSON.stringify(date)},
    sortYear: ${sortYear},
    era: ${JSON.stringify(era)},
    title: ${JSON.stringify(title)},
    textbookVersion: ${JSON.stringify(textbook)},
    actualHistory: ${JSON.stringify(actual)},
    historicalRebuttals: [
${reb}
    ],
    sources: [${sources.map(s=>`h.${s}`).join(", ")}],
    categories: [${categories.map(c=>JSON.stringify(c)).join(",")}],${related ? `\n    relatedEvents: [${related.map(r=>JSON.stringify(r)).join(", ")}],` : ""}
  },`;
}

const historyEntries = [
  entry("HH-1675-KING-PHILIP", "1675-1676", 1675, "Colonial", "King Philip's War",
    "Colonial New England expanded peacefully through settlement.",
    "War devastated Native nations; survivors lost land, autonomy, and lives to English expansion.",
    [["Natives attacked settlers first.", "Colonists seized land and violated agreements; Indigenous resistance was a response to dispossession.", ["king_philips_war"]]],
    ["king_philips_war"], ["Native","Military"]),
  entry("HH-1676-BACON", "1676", 1676, "Colonial", "Bacon's Rebellion",
    "A frontier revolt about taxes and Indian policy.",
    "After poor whites and Black laborers briefly allied, elites hardened race-based slavery to prevent future coalitions.",
    [["It was just about frontier defense.", "Planters used race law to break class solidarity after the rebellion.", ["bacon_rebellion"]]],
    ["bacon_rebellion"], ["Race","Labor"]),
  entry("HH-1739-STONO", "1739", 1739, "Colonial", "Stono Rebellion",
    "An isolated slave uprising with little lasting effect.",
    "South Carolina responded with the Negro Act, banning literacy, assembly, and movement for enslaved people.",
    [["Slaves were content until outsiders stirred them.", "The uprising shows resistance; the legal crackdown shows how terror maintained slavery.", ["stono"]]],
    ["stono"], ["Race","Labor"]),
  entry("HH-1782-GNADENHUTTEN", "1782", 1782, "Revolution", "Gnadenhutten Massacre",
    "Frontier violence was mutual and chaotic.",
    "Pennsylvania militia murdered 96 Christian Lenape civilians, mostly women and children, who had been converted and disarmed.",
    [["War is hell on all sides.", "These were noncombatant converts. The massacre was ethnic cleansing, not fog of war.", ["gnadenhutten"]]],
    ["gnadenhutten"], ["Native","Military"]),
  entry("HH-1798-ALIEN-SEDITION", "1798", 1798, "Early Republic", "Alien and Sedition Acts",
    "Early America always protected free speech.",
    "Federalists criminalized criticism of the government and targeted immigrants as political threats.",
    [["National security required it.", "They jailed newspaper editors for political speech. That is repression, not security.", ["alien_sedition"]]],
    ["alien_sedition"], ["Democracy","Education"]),
  entry("HH-1831-NAT-TURNER", "1831", 1831, "Antebellum", "Nat Turner's Rebellion",
    "Slave rebellions were rare because slavery was mild.",
    "After Turner's uprising, Southern states banned Black literacy and tightened patrols; terror was the maintenance system.",
    [["Turner proves slavery needed harsh control.", "Literacy bans prove the system feared educated enslaved people, not that it was gentle.", ["nat_turner"]]],
    ["nat_turner"], ["Race","Democracy"]),
  entry("HH-1838-TRAIL-TEARS", "1838-1839", 1838, "Antebellum", "Trail of Tears",
    "Native tribes relocated voluntarily to better land.",
    "Federal troops forced Cherokee and other nations west; thousands died of disease, exposure, and starvation.",
    [["They signed treaties.", "Treaties were coerced after gold discovery and Georgia seizure of Cherokee land.", ["trail_of_tears","indian_removal_crs"]]],
    ["trail_of_tears","indian_removal_crs"], ["Native","Military"], ["HH-1830-REMOVAL"]),
  entry("HH-1846-MEXICAN-WAR", "1846-1848", 1846, "Antebellum", "Mexican-American War",
    "Manifest Destiny peacefully fulfilled America's continental destiny.",
    "The U.S. provoked war and seized roughly half of Mexico, expanding slavery's potential footprint.",
    [["Mexico started it.", "Polk ordered troops into disputed territory. The war was expansion for land and slavery politics.", ["mexican_american_war"]]],
    ["mexican_american_war"], ["Foreign Policy","Military"]),
  entry("HH-1866-CONVICT-LEASE", "1865-1928", 1866, "Reconstruction", "Convict Leasing",
    "The 13th Amendment ended forced labor forever.",
    "The amendment's punishment clause enabled leasing of Black prisoners to mines and plantations under Jim Crow criminalization.",
    [["They were criminals.", "Vagrancy laws criminalized unemployment. Forced labor continued under a new legal label.", ["convict_leasing","black_codes"]]],
    ["convict_leasing","black_codes"], ["Race","Labor"]),
  entry("HH-1871-CHINESE-MASSACRE", "1871", 1871, "Gilded Age", "Chinese Massacre of 1871",
    "Anti-Chinese violence was rare fringe crime.",
    "A Los Angeles mob lynched 18 Chinese immigrants in one of the largest mass lynchings in U.S. history.",
    [["It was just a riot.", "It was a racial massacre that previewed the Chinese Exclusion Act.", ["chinese_massacre_1871","chinese_exclusion"]]],
    ["chinese_massacre_1871","chinese_exclusion"], ["Race","Labor"]),
  entry("HH-1887-DAWES", "1887", 1887, "Gilded Age", "Dawes Act",
    "Allotment helped Indians become independent farmers.",
    "The law broke communal landholding and transferred tens of millions of acres to white settlers and corporations.",
    [["Private property civilizes.", "Allotment was land theft dressed as reform. Tribal sovereignty and wealth were destroyed.", ["dawes_act"]]],
    ["dawes_act"], ["Native","Economy"]),
  entry("HH-1898-WILMINGTON", "1898", 1898, "Gilded Age", "Wilmington Massacre",
    "Southern Redemption restored order after Reconstruction chaos.",
    "Armed white supremacists overthrew a biracial elected government and killed dozens of Black residents.",
    [["It was a race riot on both sides.", "It was a coup. The perpetrators published their plan to seize power by force.", ["wilmington_1898"]]],
    ["wilmington_1898"], ["Race","Democracy"]),
  entry("HH-1917-BISBEE", "1917", 1917, "WWI", "Bisbee Deportation",
    "Wartime required unity against radical strikers.",
    "Armed deputies kidnapped and dumped over 1,000 striking miners in the desert without trial.",
    [["They were dangerous IWW agitators.", "Due process does not vanish because bosses dislike a union. This was corporate vigilantism.", ["bisbee"]]],
    ["bisbee"], ["Labor","Democracy"]),
  entry("HH-1917-CREEL", "1917-1919", 1917, "WWI", "Creel Committee Propaganda",
    "Americans freely supported WWI without government spin.",
    "Wilson's Committee on Public Information ran a mass propaganda machine to sell the war and smear dissent.",
    [["It was just public information.", "It was state propaganda paired with Espionage Act prosecutions of anti-war speech.", ["creel_committee","espionage_act"]]],
    ["creel_committee","espionage_act"], ["Democracy","Education"]),
  entry("HH-1919-RED-SUMMER", "1919", 1919, "Roaring 20s", "Red Summer",
    "Postwar race riots were spontaneous urban disorder.",
    "White mobs attacked Black communities in dozens of cities; Black veterans returning from WWI were frequent targets.",
    [["Both sides rioted.", "White mobs initiated massacres. Federal and local authorities often sided with attackers.", ["red_summer"]]],
    ["red_summer"], ["Race","Military"]),
  entry("HH-1919-PALMER", "1919-1920", 1919, "Roaring 20s", "Palmer Raids",
    "Raids protected America from communist bombs.",
    "Mass arrests and deportations targeted immigrants and radicals with little evidence and no due process.",
    [["They were terrorists.", "Guilt by association and warrantless raids are police-state tactics, not justice.", ["palmer_raids"]]],
    ["palmer_raids"], ["Democracy","Labor"]),
  entry("HH-1924-IMMIGRATION", "1924", 1924, "Roaring 20s", "Immigration Act of 1924",
    "Quotas were neutral population management.",
    "National-origin formulas locked in Northern European preference and barred Asian immigration using eugenic logic.",
    [["We just wanted orderly immigration.", "The law was explicitly racial. Legislators cited eugenics and white purity openly.", ["immigration_1924"]]],
    ["immigration_1924"], ["Race","Democracy"]),
  entry("HH-1924-INDIAN-CITIZEN", "1924", 1924, "Roaring 20s", "Indian Citizenship Act",
    "Citizenship immediately equalized Native rights.",
    "Many states still blocked Native voting; citizenship did not restore stolen land or end guardianship controls.",
    [["They finally got full equality.", "Paper citizenship without voting access or land rights is not equality.", ["citizenship_1924"]]],
    ["citizenship_1924"], ["Native","Democracy"]),
  entry("HH-1927-BUCK-V-BELL", "1927", 1927, "Roaring 20s", "Buck v. Bell",
    "Eugenics was fringe pseudoscience America never embraced.",
    "The Supreme Court upheld forced sterilization; tens of thousands were sterilized under state laws.",
    [["Oliver Wendell Holmes settled it.", "Three generations of imbeciles is enough is not science. It is state violence against the disabled.", ["buck_v_bell"]]],
    ["buck_v_bell"], ["Healthcare","Democracy"]),
  entry("HH-1931-SCOTTSBORO", "1931", 1931, "Depression", "Scottsboro Boys",
    "Southern courts fairly tried sensational cases.",
    "Nine Black teens faced death on false rape charges; all-white juries and rushed trials exposed Jim Crow justice.",
    [["The courts handled it.", "It took years of appeals and national pressure because the system was designed to convict Black defendants.", ["scottsboro"]]],
    ["scottsboro"], ["Race","Democracy"]),
  entry("HH-1931-REPATRIATION", "1929-1936", 1931, "Depression", "Mexican Repatriation",
    "Only illegal immigrants were sent back during the Depression.",
    "Local and federal campaigns forced out hundreds of thousands of Mexican Americans, including U.S. citizens.",
    [["They went voluntarily.", "Raids, threats, and denial of relief coerced departures. Citizenship did not protect people.", ["mexican_repatriation"]]],
    ["mexican_repatriation"], ["Race","Labor"]),
  entry("HH-1934-IRA", "1934", 1934, "Depression", "Indian Reorganization Act",
    "The New Deal fully restored tribal sovereignty.",
    "The IRA ended allotment but imposed federal constitutional templates and continued Interior Department oversight.",
    [["Roosevelt fixed Indian policy.", "Ending allotment mattered, but sovereignty under federal supervision is still constrained sovereignty.", ["indian_reorg","dawes_act"]]],
    ["indian_reorg"], ["Native","Democracy"]),
  entry("HH-1937-MEMORIAL-DAY", "1937", 1937, "Depression", "Memorial Day Massacre",
    "Police kept order during a violent steel strike.",
    "Chicago police killed 10 unarmed strikers and wounded dozens during a peaceful march.",
    [["Strikers attacked first.", "Newsreel and photos show police firing on a retreating crowd. Labor was met with bullets.", ["memorial_day_massacre"]]],
    ["memorial_day_massacre"], ["Labor","Democracy"]),
  entry("HH-1942-BRACERO", "1942-1964", 1942, "WWII", "Bracero Program",
    "Guest workers were treated as valued wartime partners.",
    "Contracts underpaid Mexican laborers, withheld wages, and left workers dependent on employers with weak enforcement.",
    [["It was temporary help.", "It was a labor-control system that treated workers as disposable while agribusiness profits rose.", ["bracero"]]],
    ["bracero"], ["Labor","Race"]),
  entry("HH-1943-ZOOT", "1943", 1943, "WWII", "Zoot Suit Riots",
    "Wartime sailors defended themselves against gangs.",
    "Service members and police targeted Mexican American youth; media blamed the victims' clothing and culture.",
    [["It was about gangs.", "Stripping and beating kids for fashion is racial terror, not crime control.", ["zoot_suit"]]],
    ["zoot_suit"], ["Race","Military"]),
  entry("HH-1944-GI-BILL", "1944", 1944, "WWII", "G.I. Bill Exclusion",
    "The G.I. Bill created a colorblind middle class.",
    "Local banks, colleges, and officials steered benefits to white veterans, widening the racial wealth gap.",
    [["Anyone who served could use it.", "Redlining and segregated campuses blocked Black veterans from the same home and education wealth.", ["gi_bill_exclusion","redlining_hud"]]],
    ["gi_bill_exclusion","redlining_hud"], ["Race","Economy"]),
  entry("HH-1954-WETBACK", "1954", 1954, "Cold War", "Operation Wetback",
    "Only illegal entrants were removed.",
    "The campaign used racial profiling and swept up U.S. citizens and legal residents of Mexican descent.",
    [["Borders must be enforced.", "Citizenship papers did not stop deportation buses. That is ethnic cleansing logistics, not neutral enforcement.", ["operation_wetback"]]],
    ["operation_wetback"], ["Race","Foreign Policy"]),
  entry("HH-1964-BRAZIL", "1964", 1964, "Cold War", "Brazil Coup",
    "Brazil's military acted alone against communism.",
    "The U.S. backed the overthrow of an elected government, opening two decades of dictatorship.",
    [["We supported democracy abroad.", "Backing a coup against an elected president is the opposite of democracy promotion.", ["brazil_coup_1964"]]],
    ["brazil_coup_1964"], ["Foreign Policy","Military"], ["HH-1954-GUATEMALA"]),
  entry("HH-1965-VRA", "1965", 1965, "Civil Rights", "Voting Rights Act",
    "The VRA permanently ended voting discrimination.",
    "The Act banned literacy tests and required preclearance; Shelby County later gutted the preclearance regime.",
    [["Jim Crow is over forever.", "The VRA worked because of federal oversight. Strip oversight and the old tactics return in new clothes.", ["voting_rights_1965","shelby_county"]]],
    ["voting_rights_1965"], ["Democracy","Race"]),
  entry("HH-1971-PENTAGON-PAPERS", "1971", 1971, "Vietnam", "Pentagon Papers",
    "Presidents leveled with the public about Vietnam.",
    "A secret DoD study showed decades of official deception about the war's progress and purpose.",
    [["Leaks endanger troops.", "Lying a nation into endless war endangers troops. The papers proved the public was misled.", ["pentagon_papers","gulf_of_tonkin"]]],
    ["pentagon_papers"], ["Military","Democracy"]),
  entry("HH-1971-WAR-ON-DRUGS", "1971", 1971, "Vietnam", "War on Drugs Launch",
    "Drug policy was a race-neutral public health effort.",
    "Nixon's drug war expanded policing and sentencing that produced mass incarceration of Black and Brown Americans.",
    [["Drugs destroy communities.", "Selective enforcement and sentencing disparities show the war targeted people more than chemicals.", ["war_on_drugs","mass_incarceration_bjs"]]],
    ["war_on_drugs","mass_incarceration_bjs"], ["Race","Healthcare"]),
  entry("HH-1972-WILLOWBROOK", "1972", 1972, "Vietnam", "Willowbrook Exposure",
    "Institutions cared for the disabled when families could not.",
    "Investigations found overcrowding, abuse, and unethical medical experiments on disabled children.",
    [["It was a few bad apples.", "Warehousing disabled people without rights was policy, not accident. It fueled the disability rights movement.", ["willowbrook","section_504"]]],
    ["willowbrook"], ["Healthcare","Democracy"]),
  entry("HH-1973-WOUNDED-KNEE-OCC", "1973", 1973, "Vietnam", "Wounded Knee Occupation",
    "AIM radicals seized a town for publicity.",
    "Activists occupied Wounded Knee to protest treaty violations, corruption, and unbroken colonial control.",
    [["They were violent militants.", "They demanded treaty enforcement. The government answered with armored vehicles and a media blackout.", ["wounded_knee_1973","wounded_knee"]]],
    ["wounded_knee_1973"], ["Native","Democracy"]),
  entry("HH-1975-CHURCH", "1975", 1975, "Vietnam", "Church Committee",
    "Intelligence agencies always respected civil liberties.",
    "Senate investigations proved COINTELPRO, assassination plots, and illegal domestic spying as policy.",
    [["A few rogue agents.", "The committee documented programs approved at the highest levels across decades.", ["church_committee","cointelpro"]]],
    ["church_committee","cointelpro"], ["Democracy","Military"]),
  entry("HH-1975-CONDOR", "1975-1980s", 1975, "Vietnam", "Operation Condor",
    "Latin American dictatorships acted independently.",
    "Southern Cone regimes coordinated disappearances with U.S. intelligence awareness and support.",
    [["We fought communism.", "Disappearing students and unionists is state terror. Anti-communism was the cover story.", ["operation_condor","chile_coup"]]],
    ["operation_condor"], ["Foreign Policy","Military"]),
  entry("HH-1977-504-SITIN", "1977", 1977, "Vietnam", "Section 504 Sit-in",
    "Disability rights arrived gently through bipartisan goodwill.",
    "Activists occupied federal buildings for weeks until Section 504 anti-discrimination rules were signed.",
    [["The government was already helping.", "Without the sit-in, regulations sat unsigned. Disabled people forced the state's hand.", ["section_504","ada_1990"]]],
    ["section_504"], ["Healthcare","Democracy"]),
  entry("HH-1978-LOVE-CANAL", "1978", 1978, "Vietnam", "Love Canal",
    "Pollution was an unfortunate local accident.",
    "Hooker Chemical buried toxins under a neighborhood; residents organized until Superfund existed.",
    [["People chose to live there.", "Families were not told about the dump. Corporate secrecy plus weak regulation created the crisis.", ["love_canal"]]],
    ["love_canal"], ["Healthcare","Economy"]),
  entry("HH-1979-TMI", "1979", 1979, "Vietnam", "Three Mile Island",
    "Nuclear power was proven perfectly safe.",
    "A partial meltdown showed how close disaster can come and how poorly the public was informed in real time.",
    [["Nobody died, so it was fine.", "Narrowly avoiding catastrophe is not proof of safety. It is a warning.", ["three_mile_island"]]],
    ["three_mile_island"], ["Healthcare","Economy"]),
  entry("HH-1981-PATCO", "1981", 1981, "Reagan era", "PATCO Firings",
    "Reagan simply enforced the law against illegal strikes.",
    "Firing over 11,000 controllers signaled open season on unions and accelerated private-sector union collapse.",
    [["Public employees cannot strike.", "The political message was larger: crush organized labor. Corporate America got the memo.", ["patco_strike","taft_hartley"]]],
    ["patco_strike"], ["Labor","Economy"]),
  entry("HH-1983-GRENADA", "1983", 1983, "Reagan era", "Invasion of Grenada",
    "The U.S. rescued students and restored democracy.",
    "The invasion overthrew Grenada's government without UN approval and fit a pattern of Caribbean intervention.",
    [["Tiny island, big threat.", "Medical students were a pretext. Regime change was the point.", ["grenada_1983"]]],
    ["grenada_1983"], ["Foreign Policy","Military"]),
  entry("HH-1986-BOWERS", "1986", 1986, "Reagan era", "Bowers v. Hardwick",
    "The Court neutrally deferred to state morals legislation.",
    "The Court upheld criminalizing private same-sex intimacy, green-lighting police intrusion into LGBTQ lives.",
    [["States rights on morals.", "Criminalizing love is not neutral federalism. It was state-sponsored queer erasure.", ["bowers_v_hardwick","lawrence_v_texas"]]],
    ["bowers_v_hardwick"], ["LGBTQ","Democracy"]),
  entry("HH-1987-FAIRNESS", "1987", 1987, "Reagan era", "Fairness Doctrine Repeal",
    "Broadcasting became freer and more competitive.",
    "Ending the Fairness Doctrine cleared the path for one-sided political talk radio and partisan media empires.",
    [["The market will balance views.", "Scarce public airwaves without balance rules rewarded outrage and propaganda business models.", ["fairness_doctrine"]]],
    ["fairness_doctrine"], ["Democracy","Education"]),
  entry("HH-1987-CANCER-ALLEY", "1980s-present", 1987, "Reagan era", "Cancer Alley",
    "Industry brings jobs; pollution is evenly shared.",
    "Petrochemical plants concentrate along the Mississippi in majority-Black Louisiana communities with elevated cancer risk.",
    [["Correlation is not causation.", "Siting patterns, emissions data, and health disparities document environmental racism, not coincidence.", ["cancer_alley","love_canal"]]],
    ["cancer_alley"], ["Race","Healthcare"]),
  entry("HH-1990-ADA", "1990", 1990, "911 era", "Americans with Disabilities Act",
    "The ADA ended disability discrimination overnight.",
    "The ADA created enforceable rights, but access fights continue over transit, employment, and institutionalization.",
    [["Problem solved in 1990.", "Rights on paper need enforcement. Disability discrimination did not vanish with a signature.", ["ada_1990","section_504"]]],
    ["ada_1990"], ["Healthcare","Democracy"]),
  entry("HH-1992-RODNEY-KING", "1992", 1992, "911 era", "LA Uprising after Rodney King",
    "A riot over one verdict.",
    "Acquittal of officers filmed beating Rodney King ignited uprising against long-standing police violence and inequality.",
    [["Just criminals looting.", "A videotaped beating plus a not-guilty verdict exposed a system Black Angelenos already knew.", ["rodney_king"]]],
    ["rodney_king"], ["Race","Democracy"]),
  entry("HH-1994-NAFTA", "1994", 1994, "911 era", "NAFTA Labor Shock",
    "Free trade lifted all boats.",
    "NAFTA accelerated offshoring, weakened manufacturing unions, and left many U.S. and Mexican workers worse off.",
    [["Cheaper goods for consumers.", "Wage stagnation and factory closures were design features of corporate-led trade rules.", ["nafta_labor"]]],
    ["nafta_labor"], ["Labor","Economy"]),
  entry("HH-1996-WELFARE", "1996", 1996, "911 era", "Welfare Reform",
    "Ending welfare as we know it reduced dependency.",
    "Time limits and block grants cut the cash safety net; deep poverty rose for many families when recessions hit.",
    [["Work requirements help.", "Punishing poverty without living wages and childcare is austerity, not empowerment.", ["welfare_reform_1996"]]],
    ["welfare_reform_1996"], ["Economy","Race"]),
  entry("HH-2003-LAWRENCE", "2003", 2003, "911 era", "Lawrence v. Texas",
    "Gay rights advanced purely through gradual culture change.",
    "The Court struck down sodomy laws, ending criminalization of private same-sex intimacy after Bowers.",
    [["The Court invented rights.", "Police in bedrooms was the invention. Lawrence restored privacy the Constitution already implies.", ["lawrence_v_texas","bowers_v_hardwick"]]],
    ["lawrence_v_texas"], ["LGBTQ","Democracy"]),
  entry("HH-2005-KATRINA", "2005", 2005, "911 era", "Hurricane Katrina",
    "A natural disaster nobody could have managed better.",
    "Levee failure, slow federal response, and racialized neglect devastated New Orleans's Black neighborhoods.",
    [["Mother Nature.", "Engineered levees failed and FEMA faltered. Policy choices determined who drowned and who was rescued.", ["katrina"]]],
    ["katrina"], ["Race","Healthcare"]),
  entry("HH-2010-CITIZENS-UNITED", "2010", 2010, "2008", "Citizens United",
    "The Court protected free speech for everyone equally.",
    "Unlimited independent spending let billionaires and corporations drown out ordinary voters.",
    [["Money is speech.", "If money is speech, then speech is unequally rationed by wealth. That is oligarchy, not democracy.", ["citizens_united_hist"]]],
    ["citizens_united_hist"], ["Democracy","Economy"]),
  entry("HH-2013-SHELBY", "2013", 2013, "Today", "Shelby County v. Holder",
    "The South outgrew Voting Rights Act oversight.",
    "The Court killed preclearance; states promptly passed voter ID, polling cuts, and purge laws previously blocked.",
    [["Racism is over.", "Immediate restrictive laws after Shelby prove why preclearance existed.", ["shelby_county","voting_rights_1965"]]],
    ["shelby_county","voting_rights_1965"], ["Democracy","Race"], ["HH-1965-VRA"]),
  entry("HH-2013-PRISM", "2013", 2013, "Today", "PRISM / Snowden Disclosures",
    "Post-Church Committee reforms permanently ended mass domestic spying.",
    "Snowden showed NSA bulk collection of Americans' communications under secret interpretations of law.",
    [["If you have nothing to hide.", "Secret mass surveillance recreates COINTELPRO capacity with better computers.", ["snowden_prism","church_committee","patriot_act"]]],
    ["snowden_prism","patriot_act"], ["Democracy","Military"]),
  entry("HH-2014-FLINT", "2014-2019", 2014, "Today", "Flint Water Crisis",
    "An unfortunate municipal mistake.",
    "Cost-cutting switched Flint to corrosive river water; officials denied lead poisoning while children were harmed.",
    [["Local incompetence only.", "Austerity plus disregard for a majority-Black city produced environmental injustice.", ["flint_water","cancer_alley"]]],
    ["flint_water"], ["Race","Healthcare"]),
  entry("HH-2015-OBERGEFELL", "2015", 2015, "Today", "Obergefell v. Hodges",
    "Marriage equality was inevitable cultural drift.",
    "The Court held same-sex couples have a constitutional right to marry after decades of organizing and litigation.",
    [["Judges invented marriage.", "Equal protection is not invention. Denying civil marriage was the invention.", ["obergefell"]]],
    ["obergefell"], ["LGBTQ","Democracy"]),
  entry("HH-2016-PULSE", "2016", 2016, "Today", "Pulse Nightclub Massacre",
    "A lone-wolf tragedy unrelated to politics.",
    "A gunman murdered 49 people at a LGBTQ nightclub, exposing ongoing vulnerability of queer public space.",
    [["Don't politicize tragedy.", "Targeting a gay club is political violence. Erasing that context is another form of erasure.", ["pulse_orlando"]]],
    ["pulse_orlando"], ["LGBTQ","Democracy"]),
  entry("HH-2017-CHARLOTTESVILLE", "2017", 2017, "Trump era", "Unite the Right",
    "Very fine people on both sides of a statue debate.",
    "Neo-Nazis and white nationalists marched with torches; a counter-protester was murdered with a car.",
    [["Both sides.", "One side chanted Jews will not replace us. Equivalence is a lie.", ["charlottesville"]]],
    ["charlottesville"], ["Race","Democracy"]),
  entry("HH-2018-FAMILY-SEP", "2018", 2018, "Trump era", "Family Separation",
    "Parents who cross illegally choose family separation.",
    "Zero-tolerance prosecution deliberately separated thousands of children as deterrence, creating lasting trauma.",
    [["Enforce the law.", "Using toddlers as deterrents is cruelty as policy. Courts and inspectors general documented the chaos.", ["family_separation"]]],
    ["family_separation"], ["Race","Democracy"]),
  entry("HH-2020-FLOYD", "2020", 2020, "Trump era", "George Floyd Uprising",
    "A single bad officer and outside agitators.",
    "Floyd's murder under a knee was filmed; protests named a national pattern of police violence and impunity.",
    [["Crime is the real issue.", "A man was killed for allegedly using a counterfeit $20. Impunity is the crisis.", ["floyd_2020"]]],
    ["floyd_2020"], ["Race","Democracy"]),
  entry("HH-2022-DOBBS", "2022", 2022, "Today", "Dobbs Overturns Roe",
    "The Court returned abortion to the people.",
    "Dobbs ended federal abortion rights; states immediately imposed bans without exceptions many voters support.",
    [["Democracy via state legislatures.", "A right that depends on your ZIP code is not liberty. It is forced birth by geography.", ["dobbs"]]],
    ["dobbs"], ["Healthcare","Democracy"]),
].join("\n");

// Apply history citations
{
  const file = data("history-citations.ts");
  let src = readFileSync(file, "utf8");
  if (!src.includes("Pass 26 expansions")) {
    src = src.replace(/\n};\s*$/, ",\n" + historyCitations + "\n};\n");
    writeFileSync(file, src);
    console.log("history citations OK");
  } else console.log("history citations already present");
}

// Apply history entries
{
  const file = data("hidden-history.ts");
  let src = readFileSync(file, "utf8");
  if (!src.includes("HH-2022-DOBBS")) {
    src = src.replace(/\n\];\s*\n\nexport function getHistoryEntryById/, "\n" + historyEntries + "\n];\n\nexport function getHistoryEntryById");
    writeFileSync(file, src);
    console.log("history entries OK");
  } else console.log("history entries already present");
}

console.log("History phase done. Entries target check next.");
